### ISSUE TITLE
Auto login not working

### ISSUE THREAD

**Issue by karwosts** [m16p/chase-offer-monitor#5]
When you mention that auto login isn't working, are you looking at what's happening in the browser? 

When I run this it looks like chase is providing a slightly different version of the website in which instead of showing the username and password fields, it just shows a button which says "Sign In", so your script isn't finding the inputs its looking for. 

Have you noticed the same?

You might consider trying to login from this link instead: https://chaseonline.chase.com/Logon.aspx?LOB=RBGLogon

It seems a little less JS heavy so maybe plays less tricks, though it does say it is out of date. 

When I tried using this page I was able to auto-login pretty easy after updating the field names, however chase threw a 2FA challenge at me and I wasn't able to solve it before the .wait in the script timed out and terminated the session. I'll need to figure out some way to get around the 2FA with this electron browser before I can proceed to testing the offer scraping.

**Comment by m16p** [comment]
I did some more debugging, I think it is because the login fields are within a separate iframe.  [This package](https://www.npmjs.com/package/nightmare-iframe) looks like what we need to add (and the example is spot-on for us too :))

I'll see if I can get it to work with that.

In answer to your question about what happened when I ran it, the username/password text-fields would always show for me (because I'd maximize the window before the page fully loaded), but Nightmare would never be able to find the textfields using the queryselectors I gave it.

**Comment by m16p** [comment]
Hmmm, that package doesn't work anymore.  There is [this one](https://github.com/rosshinkley/nightmare-iframe-manager), but it very clearly says "This is dangerous and fragile" :/  And sounds like the general Nightmare implementers have no plans to ever support iframes :/

So, not sure what to do.  Personally, I'm inclined to just get rid of the auto-login feature since I don't use it anyway, but maybe others really like it...

**Comment by karwosts** [comment]
Don't want to use that alternative URL? That's working fine for me.

**Comment by m16p** [comment]
Okay, switched to that.  I'm a bit worried it'll stop working at some point, though may as well use that while it does.

Thanks for your help!
